name: chat_ui_stream_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # stream chat
  stream_chat_flutter: ^0.2.20+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true